version: '3'

services:
  db_cinerex:
    image: postgres:14.3
    restart: always
    ports:
      - '5433:5432'
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DATABASE}
    container_name: cinerex_db
    volumes:
      - ./postgres-cinerex:/var/lib/postgresql/data
