version: '3'

services:
  db_cinerex:
    image: postgres:14.3
    restart: always
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DATABASE}
    container_name: cinerex_db
    volumes:
      - ./postgres-cinerex:/var/lib/postgresql/datav
    env_file: # <--- ADD THIS LINE
      - .env  # <--- ADD THIS LINE
  backend:
    build: .
    container_name: backend_cinerex
    restart: always
    ports:
      - '4000:4000'
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - db_cinerex
    command: ["./wait-for-it.sh", "db_cinerex", "5432", "--", "npm", "run", "start:dev"]
    env_file:
      - .env
